### ISSUE TITLE
Do you have the code/model you used to generate figure 4?

### ISSUE THREAD

**Issue by YuShenLu** [nickboucher/imperceptible#2]
I am trying to visually identify homoglyphs and I was wondering about the details of models/hyperparameters you use to create figure 4. I needed stronger homoglyph mappings than the official unicode one... You mentioned that **well-tuned** unsupervised clustering algorithms can help the process, can you provide some guidance on this? Thanks!

**Comment by YuShenLu** [comment]
Found it, nvm. Thank you for the great work

**Comment by nickboucher** [comment]
Glad to hear! If there's anything else you have trouble locating later, please feel free to re-open this issue.
