### ISSUE TITLE
wget: unable to resolve host address ‘max-cdn.cdn.appdomain.cloud

### ISSUE THREAD

**Issue by rebibabo** [nickboucher/imperceptible#3]
Hello,
I'm getting into this trouble while running the shell setup.sh, the same error happens when download files from https://ndownloader.figshare.com/files/7394542, how to resolve this problem?

Best regards,
Rebibabo

**Comment by nickboucher** [comment]
Hi Rebibabo,

That's strange -- I just ran the `setup.sh` script on a clean Google Colab instance and it worked without any errors (including downloading the referenced file).

Is there any specific error message that you're seeing? Perhaps there's some DDOS protections that are misbehaving that would be resolved if you ran from a different network?

Best,
Nicholas

**Comment by rebibabo** [comment]
Thank you very much! I just tried to rebuild the DNS cache by running the command `ipconfig /flushdns` in windows, and changed a VPN network, it did work! I'll copy it into the linux vm.

**Comment by nickboucher** [comment]
Glad to hear!

**Comment by rebibabo** [comment]
I'm sorry that I still can't download the file from https://max-cdn.cdn.appdomain.cloud/max-toxic-comment-classifier/1.0.0/assets.tar.gz, I tried all the ways to solve the network problem, and it showed the "dns_probe_finished_nxdomain" error, I'll be very appreciated if you could send the offline files "assets.tar.gz" to my mailbox rebibabo2@gmail.com.

**Comment by nickboucher** [comment]
Hi Rebibabo,

Ah, it appears that IBM has moved the location of this model. I've just pushed an update to the `setup.sh`. If that doesn't fix the issue, please let me know.

Thanks for catching this!

Best,
Nicholas

**Comment by rebibabo** [comment]
It works! Thank you very much!
