### ISSUE TITLE
Simple Translation Example

### ISSUE THREAD

**Issue by vsahil** [nickboucher/imperceptible#4]
Do you have a simple code example of translating an english sentence into the 4 kinds of pertubations, the kind you on the website https://imperceptible.soc.srcf.net/

**Comment by nickboucher** [comment]
Hi @vsahil, yes -- the perturbation function (client-side JS) used at the link above is defined [here](https://github.com/nickboucher/imperceptible/blob/2d55bb145d5592f5a981893d08cf1e2a95248de2/website/src/views/Generate.js#L67). This implementation performs random perturbations and does not use any optimization functions against a target model, which is how it can execute quickly in a browser.

If you're interested in targeting a specific model, [this notebook](https://github.com/nickboucher/imperceptible/blob/main/notebooks/Imperceptible%20Perturbations.ipynb) walks through some examples of how to implement.
